### ISSUE TITLE
Terminates with error "`encode': wrong number of arguments"

### ISSUE THREAD

**Issue by donut** [lolcommits/lolcommits#410]
When I run `$ lolcommits` I get this error:

```
#<Thread:0x00007fac93112230 /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:962 run> terminated with exception (report_on_exception is true):
/Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1054:in `encode': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1054:in `normalize_encoding'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `block in run_command'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `map'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `run_command'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:963:in `block (2 levels) in command'
/Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1054:in `encode': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1054:in `normalize_encoding'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `block in run_command'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `map'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:1062:in `run_command'
	from /Users/donut/.gem/ruby/3.0.0/gems/git-1.6.0/lib/git/lib.rb:963:in `block (2 levels) in command'
```

My system:

```
2018 15" MacBook Pro
macOS 11.1
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
imagemagick: stable 7.0.10-58
```

**Comment by donut** [comment]
Looks like lolcommits is incompatible with Ruby 3.X. Seems like downgrading to 2.7 will work, but I haven't had a chance to complete that process.

**Comment by matthutchinson** [comment]
Thanks for reporting I’ll look into it today at some point.

**Comment by donut** [comment]
Confirming that downgrading Ruby to 2.7 fixed the issue for me.

**Comment by matthutchinson** [comment]
The issue is with the git gem, upgrading that dependency fixes it, but I've got another issue with the (now very old) mercurial-ruby gem - which is broken in Ruby 3.0.

**Comment by matthutchinson** [comment]
I'm deciding what to do about that, then will post a new version of lolcommits so at the least its working with git

**Comment by matthutchinson** [comment]
OK, I have a fix, its another patch to mercurial-ruby (we have 2 other already) - will release new version asap. 
Might be time to change this dependency to something that's actually maintained.

**Comment by matthutchinson** [comment]
@donut  [0.16.3](https://rubygems.org/gems/lolcommits) should work for you now

**Comment by donut** [comment]
It's working. Thank you!
